### ISSUE TITLE
ReferenceError: convertedFunction is not defined

### ISSUE THREAD

**Issue by jasonify** [dpnishant/jsprime#10]
I just tried out the node server.js with some code (about 2k loc):

ReferenceError: convertedFunction is not defined

/home/jason/playground/jsprime/jsprime-node/engine.js:149
            convertedFunction.push(newFunction2);
            ^
ReferenceError: convertedFunction is not defined
    at Object.asignFunctionReturnValue (/home/jason/playground/jsprime/jsprime-node/engine.js:149:13)
    at IncomingMessage.<anonymous> (/home/jason/playground/jsprime/jsprime-node/server.js:71:18)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

Any ideas?

Thanks

**Comment by TejaswiniU** [comment]
Add ** exports.convertedFunction= convertedFunction;**  in analyzer.js 
This would work
